In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch
print(torch.__version__)

2.10.0+cpu


In [3]:
#torch.cuda.is_available()
#torch.cuda.get_device_name()

In [4]:
torch.empty(2, 3)

tensor([[1.7665e+10, 4.3765e-41, 1.7665e+10],
        [4.3765e-41, 2.3927e-31, 4.3765e-41]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.1614, 0.0977, 0.1867],
        [0.5828, 0.2111, 0.5732]])

In [8]:
torch.manual_seed(42)  # manual_seed: so that each time random item remain same whenever we recall this matrix tenson
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
print(torch.arange(1,5))
print(torch.arange(1,5,0.5))

tensor([1, 2, 3, 4])
tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])


In [11]:
print(torch.linspace(1,5,10))

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])


In [12]:
print(torch.eye(7)) # for identity matrix

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])


In [13]:
torch.full((3,3), 5) # matrix 3 by 3, and 5 each item

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# shape

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])   # to know shape
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)     # when want empty tensor with the same shape of x

tensor([[    134141769391504,           360964080,                   0],
        [                  0,                   0, 7310593858020254331]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
# But when we use rand_like(x), code will break because rand function create float value
# to resolve it we have to define first data type useing dtype
torch.rand_like(x, dtype = (torch.float32))   # ye sirf tab hi chalega jab data type explicitly bata do

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

# Data types

In [19]:
x.dtype

torch.int64

In [20]:
# Allocating data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype = (torch.float64))

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# Changing data type using "to" function.
print("data type of x earlier ========================:", x.dtype)
print(x.to(torch.float64))

data type of x earlier ========================: torch.int64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


# scaler operations

In [23]:
x +2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [24]:
x -3

tensor([[-2, -1,  0],
        [ 1,  2,  3]])

In [25]:
x//3

tensor([[0, 0, 1],
        [1, 1, 2]])

# element wise operations

In [26]:
torch.manual_seed(42)
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [27]:
a + b

tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])

In [28]:
a * b

tensor([[0.2264, 0.7262, 0.3602],
        [0.1278, 0.3649, 0.3567]])

In [29]:
# to find absolute value of each items: it convert all values into positive values
torch.manual_seed(3)
a = torch.rand(3,2)

In [30]:
# to make negative using neg
b = torch.neg(a)
torch.abs(b)

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270],
        [0.4716, 0.0601]])

In [31]:
# to make values round or integers
torch.round(b)

tensor([[-0., -0.],
        [-0., -0.],
        [-0., -0.]])

In [32]:
# to find ceil values
d = torch.rand(3,2, dtype = torch.float64)
print(d)
torch.ceil(d)

tensor([[0.1749, 0.7554],
        [0.6083, 0.1987],
        [0.4334, 0.4048]], dtype=torch.float64)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [33]:
torch.floor(d)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

# reduction operations

In [34]:
e = torch.randint(size =(3,2), low = 0, high = 10, dtype = torch.float64)
print(e)

tensor([[0., 4.],
        [6., 9.],
        [1., 6.]], dtype=torch.float64)


In [35]:
torch.sum(e)

tensor(26., dtype=torch.float64)

In [36]:
# sum column wise
torch.sum(e, dim = 0)

tensor([ 7., 19.], dtype=torch.float64)

In [37]:
# sum row wise
torch.sum(e, dim = 1)

tensor([ 4., 15.,  7.], dtype=torch.float64)

In [38]:
# mean, it work when data type float ho
torch.mean(e)

tensor(4.3333, dtype=torch.float64)

In [39]:
# mean column wise
torch.mean(e, dim = 0)

tensor([2.3333, 6.3333], dtype=torch.float64)

In [40]:
# median, max and min: poore tensor ke upar bhi or kisi column or row ke upar bhi karsakte h
print("mean of tensor:", torch.mean(e))
print("mean of columns:", torch.mean(e, dim = 0))
print("mean of rows:", torch.mean(e, dim = 1))

mean of tensor: tensor(4.3333, dtype=torch.float64)
mean of columns: tensor([2.3333, 6.3333], dtype=torch.float64)
mean of rows: tensor([2.0000, 7.5000, 3.5000], dtype=torch.float64)


In [41]:
# product, std, variance
print("product:", torch.prod(e))
print("std:", torch.std(d))
print("var:", torch.var(e))

product: tensor(0., dtype=torch.float64)
std: tensor(0.2266, dtype=torch.float64)
var: tensor(11.4667, dtype=torch.float64)


In [42]:
# argmax, argmin: dono matrix ke andar ki sabse badi or choti value batate h
print("argmax:", torch.argmax(e))
print("argmin:", torch.argmin(e))

argmax: tensor(3)
argmin: tensor(0)


# matrix multiplications

In [43]:
torch.manual_seed(4)
f = torch.randint(size = (3,2), low = 0, high = 10)
g = torch.randint(size = (2, 3), low = 0, high = 10)

In [44]:
# matrix multiplication
torch.matmul(f, g)

tensor([[  4,  32,  24],
        [ 12,  30,  20],
        [ 87, 102,  54]])

In [45]:
# dot product
torch.manual_seed(4)
h = torch.rand(5)
i = torch.rand(5)
print(h)
print(i)

torch.dot(h, i)

tensor([0.5596, 0.5591, 0.0915, 0.2100, 0.0072])
tensor([0.0390, 0.9929, 0.9131, 0.6186, 0.9744])


tensor(0.7973)

In [46]:
# transpose
j = torch.rand(3,2)
print(j)
torch.transpose(j, 0, 1) # yahan 0 "column" ko 1 "row" se swap karna chahta hu

tensor([[0.3189, 0.2148],
        [0.9263, 0.4735],
        [0.5949, 0.7956]])


tensor([[0.3189, 0.9263, 0.5949],
        [0.2148, 0.4735, 0.7956]])

In [47]:
# determinant
k = torch.rand(3,3)
torch.det(k)

tensor(0.1840)

In [48]:
# inverse
print(k)
torch.inverse(k)

tensor([[0.7635, 0.2137, 0.3066],
        [0.0386, 0.5220, 0.3207],
        [0.6074, 0.5233, 0.9263]])


tensor([[ 1.7158, -0.2038, -0.4974],
        [ 0.8647,  2.8313, -1.2666],
        [-1.6136, -1.4658,  2.1213]])

In [49]:
a = torch.rand(3,3)
b = torch.rand(3,3)

# greater than
a > b
# less than
a< b
# leass than equal to
a != b
# equal to
a ==b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

# special fucntions

In [50]:
a = torch.randint(size = (3,2), low = 1, high = 5, dtype = torch.float64)

# log
torch.log(a)

tensor([[1.0986, 1.3863],
        [0.0000, 0.0000],
        [1.3863, 1.0986]], dtype=torch.float64)

In [51]:
# exponent
torch.exp(a)

tensor([[20.0855, 54.5982],
        [ 2.7183,  2.7183],
        [54.5982, 20.0855]], dtype=torch.float64)

In [52]:
# sqrt
torch.sqrt(a)

tensor([[1.7321, 2.0000],
        [1.0000, 1.0000],
        [2.0000, 1.7321]], dtype=torch.float64)

In [53]:
# sigmoid
torch.sigmoid(a)     # make sure all tensors values in float to run this function

tensor([[0.9526, 0.9820],
        [0.7311, 0.7311],
        [0.9820, 0.9526]], dtype=torch.float64)

In [54]:
# relu
torch.relu(a)

tensor([[3., 4.],
        [1., 1.],
        [4., 3.]], dtype=torch.float64)

# Inplace operations

In [55]:
# when we add m + n a new tensor is created uses memory and space.
# agar hame n ko m me jodna h or ham ye bhi nhi chahte ki extra space use ho uske liye ham add_ function use karte h
m = torch.randint(size = (3,2), low = 1, high = 5, dtype = torch.float32)
n = torch.randint(size = (3,2), low = 1, high = 5, dtype = torch.float32)
print(m)
print(n)

# adding n in m
m.add_(n)

tensor([[2., 2.],
        [1., 3.],
        [2., 1.]])
tensor([[4., 3.],
        [4., 4.],
        [3., 4.]])


tensor([[6., 5.],
        [5., 7.],
        [5., 5.]])

In [56]:
m

tensor([[6., 5.],
        [5., 7.],
        [5., 5.]])

In [57]:
# similarly agar ham relu ke aage underscore (relu_) lage de to wo inplace operation karega
torch.relu_(m)

tensor([[6., 5.],
        [5., 7.],
        [5., 5.]])

In [58]:
# same for sigmoid
torch.sigmoid_(m)

tensor([[0.9975, 0.9933],
        [0.9933, 0.9991],
        [0.9933, 0.9933]])

# copy tensor

In [59]:
a = torch.rand(3,2)
b = torch.rand(3,2)

b = a

In [60]:
b

tensor([[0.7985, 0.0183],
        [0.8257, 0.5542],
        [0.8089, 0.6975]])

In [61]:
a

tensor([[0.7985, 0.0183],
        [0.8257, 0.5542],
        [0.8089, 0.6975]])

In [62]:
print(id(a))
print(id(b))

# both will show same memory id, means change in b cause change in a, which may be problem in future operations

134140628418096
134140628418096


In [63]:
# Thus we uses clone method to make copy
a = torch.clone(b)

In [64]:
print(id(a))
print(id(b))
# now both are using diff memory space

134140628469792
134140628418096


# creating tensor on gpu

In [65]:
# torch.cude.is_available()
# device = torch.device('cuda')


In [66]:
# creating new tensor
# torch.rand((3,2), device = device)

In [67]:
# transfering tensor from cpu to gpu
# a.to(device)

# reshaping tensor

In [68]:
a = torch.ones(4,4)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [69]:
# reshaping
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [70]:
# flattening
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
# using permute
a = torch.rand(2, 3, 2)
print(a)

tensor([[[0.2645, 0.2282],
         [0.9258, 0.7828],
         [0.7059, 0.3501]],

        [[0.0943, 0.6064],
         [0.9620, 0.7225],
         [0.0963, 0.4557]]])


In [72]:
a.permute(2, 0, 1)

tensor([[[0.2645, 0.9258, 0.7059],
         [0.0943, 0.9620, 0.0963]],

        [[0.2282, 0.7828, 0.3501],
         [0.6064, 0.7225, 0.4557]]])

In [73]:
# unsqeeze function
# isko tensor me nayi dimension add karne ke liye use kiya jata h

image = torch.rand(226,226,3)
image.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [74]:
# sqeeze
image.squeeze(0).shape

torch.Size([226, 226, 3])

# converting numpy into pytorch and vice versa

In [75]:
a= torch.tensor([1,2,3])

In [76]:
type(a)

torch.Tensor

In [77]:
# converting into numpy
b = a.numpy()

In [78]:
type(b)

numpy.ndarray

In [79]:
# converting numpy into tensor
import numpy as np
c = np.array([1,2,3])

In [80]:
type(torch.from_numpy(c))

torch.Tensor

In [81]:
type(c)

numpy.ndarray