In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
torch.cuda.is_available()
torch.cuda.get_device_name()

'Tesla T4'

In [3]:
torch.empty(2, 3)

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3)

tensor([[0.3560, 0.9973, 0.5553],
        [0.2421, 0.5021, 0.3126]])